from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from frontier import __version__
from frontier.errors import InstallError
from frontier.onboard.constants import GITHUB_WHEEL

REQUIRED_SECRETS = (
    "FRONTIER_API_URL",
    "FRONTIER_API_KEY",
    "FRONTIER_ENTITY_HASH_KEY",
    "SNOWFLAKE_ACCOUNT",
    "SNOWFLAKE_USER",
    "SNOWFLAKE_PASSWORD",
)

SNOWFLAKE_SECRETS = ("SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER", "SNOWFLAKE_PASSWORD")
API_SECRETS = ("FRONTIER_API_URL", "FRONTIER_API_KEY")


def workflow_path(project_dir: Path, git_root: Path | None = None) -> Path:
    root = git_root or project_dir
    return root / ".github" / "workflows" / "frontier.yml"


def render_workflow(
    *,
    runner_version: str = __version__,
    profile_name: str = "jaffle_shop",
    default_branch: str = "main",
    database: str = "DEV",
    warehouse: str = "COMPUTE_WH",
    schema: str = "DBT_CI",
    blocking: bool = False,
    python_version: str = "3.12",
) -> str:
    wheel = GITHUB_WHEEL.format(version=runner_version)
    blocking_value = "true" if blocking else "false"
    return f"""\
# Generated by `frontier setup github`.
# Do not put secrets in this file. Configure GitHub Actions secrets instead:
#   FRONTIER_API_URL, FRONTIER_API_KEY, FRONTIER_ENTITY_HASH_KEY,
#   SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, SNOWFLAKE_PASSWORD
#
# FRONTIER_BLOCKING={blocking_value} for the first verification PR.
# Entity hash key rotation changes entity fingerprints across assessments.

name: Frontier

on:
  pull_request:
    branches:
      - {default_branch}

permissions:
  contents: read
  pull-requests: write

jobs:
  frontier:
    name: Generate impact assessment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "{python_version}"

      - name: Install dbt
        run: pip install dbt-core dbt-snowflake

      - name: Create dbt profile
        env:
          SNOWFLAKE_ACCOUNT: ${{{{ secrets.SNOWFLAKE_ACCOUNT }}}}
          SNOWFLAKE_USER: ${{{{ secrets.SNOWFLAKE_USER }}}}
          SNOWFLAKE_PASSWORD: ${{{{ secrets.SNOWFLAKE_PASSWORD }}}}
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          {profile_name}:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: ${{{{ secrets.SNOWFLAKE_ACCOUNT }}}}
                user: ${{{{ secrets.SNOWFLAKE_USER }}}}
                password: ${{{{ secrets.SNOWFLAKE_PASSWORD }}}}
                database: {database}
                warehouse: {warehouse}
                schema: {schema}
                threads: 4
          EOF

      - name: dbt build
        id: dbt
        continue-on-error: true
        env:
          SNOWFLAKE_ACCOUNT: ${{{{ secrets.SNOWFLAKE_ACCOUNT }}}}
          SNOWFLAKE_USER: ${{{{ secrets.SNOWFLAKE_USER }}}}
          SNOWFLAKE_PASSWORD: ${{{{ secrets.SNOWFLAKE_PASSWORD }}}}
        run: |
          rm -rf target
          dbt deps
          dbt debug
          dbt build
          printf '%s\\n' "${{{{ github.sha }}}}" > target/frontier-artifact-sha

      - name: Compile base branch SQL
        if: always() && !cancelled()
        continue-on-error: true
        env:
          SNOWFLAKE_ACCOUNT: ${{{{ secrets.SNOWFLAKE_ACCOUNT }}}}
          SNOWFLAKE_USER: ${{{{ secrets.SNOWFLAKE_USER }}}}
          SNOWFLAKE_PASSWORD: ${{{{ secrets.SNOWFLAKE_PASSWORD }}}}
        run: |
          mkdir -p target-base
          git fetch --depth=1 origin "${{{{ github.event.pull_request.base.sha }}}}"
          git worktree add --detach /tmp/frontier-base "${{{{ github.event.pull_request.base.sha }}}}"
          (
            cd /tmp/frontier-base
            dbt deps
            dbt compile --target ci
            cp target/manifest.json "${{{{ github.workspace }}}}/target-base/manifest.json"
            if [ -d target/compiled ]; then
              rm -rf "${{{{ github.workspace }}}}/target-base/compiled"
              cp -R target/compiled "${{{{ github.workspace }}}}/target-base/compiled"
            fi
          )

      - name: Install Frontier
        if: always() && !cancelled()
        run: |
          pip install "frontier-runner[snowflake]=={runner_version}" \\
            || pip install "{wheel}" "snowflake-connector-python>=3.12,<4"
          frontier --version

      - name: Fetch semantic manifest
        id: manifest
        if: always() && !cancelled()
        env:
          FRONTIER_API_URL: ${{{{ secrets.FRONTIER_API_URL }}}}
          FRONTIER_API_KEY: ${{{{ secrets.FRONTIER_API_KEY }}}}
        run: |
          case "${{FRONTIER_API_URL}}" in
            https://*) ;;
            *)
              echo "FRONTIER_API_URL must be a public HTTPS origin" >&2
              exit 1
              ;;
          esac
          frontier manifest fetch --output target/frontier-manifest.json

      - name: Generate impact assessment
        id: prove
        if: always() && !cancelled() && steps.manifest.outcome == 'success'
        env:
          PYTHONUNBUFFERED: "1"
          FRONTIER_ENTITY_HASH_KEY: ${{{{ secrets.FRONTIER_ENTITY_HASH_KEY }}}}
          FRONTIER_BLOCKING: "{blocking_value}"
          FRONTIER_PULL_REQUEST: ${{{{ github.event.pull_request.number }}}}
          FRONTIER_BASE_SHA: ${{{{ github.event.pull_request.base.sha }}}}
        run: |
          if [ -n "${{FRONTIER_DRY_RUN}}" ]; then
            echo "FRONTIER_DRY_RUN must not be set in customer CI" >&2
            exit 1
          fi
          if [ ! -f target/frontier-manifest.json ]; then
            echo "Pinned semantic manifest is required before inspect/compare/prove" >&2
            exit 1
          fi
          if [ -f target/frontier-artifact-sha ]; then
            if [ -f target-base/manifest.json ]; then
              frontier inspect --manifest-file target/frontier-manifest.json --base-manifest target-base/manifest.json
              frontier compare --manifest-file target/frontier-manifest.json --base-manifest target-base/manifest.json
              frontier prove --target ci --manifest-file target/frontier-manifest.json --base-manifest target-base/manifest.json
            else
              frontier record-failure --manifest-file target/frontier-manifest.json --reason "base-branch dbt compile failed; no SQL to compare for ${{{{ github.sha }}}}"
            fi
          else
            frontier record-failure --manifest-file target/frontier-manifest.json --reason "dbt build failed; no current artifacts for ${{{{ github.sha }}}}"
          fi

      - name: Upload assessment
        if: always() && !cancelled() && steps.prove.outcome == 'success'
        env:
          PYTHONUNBUFFERED: "1"
          FRONTIER_API_URL: ${{{{ secrets.FRONTIER_API_URL }}}}
          FRONTIER_API_KEY: ${{{{ secrets.FRONTIER_API_KEY }}}}
          FRONTIER_BLOCKING: "{blocking_value}"
          FRONTIER_PULL_REQUEST: ${{{{ github.event.pull_request.number }}}}
          GITHUB_TOKEN: ${{{{ github.token }}}}
        run: |
          if [ ! -f target/frontier-run.json ]; then
            echo "No assessment file to upload" >&2
            exit 1
          fi
          frontier upload
"""


def validate_workflow_yaml(text: str) -> dict[str, Any]:
    try:
        loaded = yaml.safe_load(text)
    except yaml.YAMLError as error:
        raise InstallError(
            "GITHUB_WORKFLOW_INVALID",
            "The generated GitHub workflow is not valid YAML.",
            cause=str(error),
            next_action="Retry `frontier setup github`.",
            docs_path="/docs/github",
        ) from error
    if not isinstance(loaded, dict):
        raise InstallError(
            "GITHUB_WORKFLOW_INVALID",
            "The generated GitHub workflow is not a YAML mapping.",
            cause="Expected a workflow object.",
            next_action="Retry `frontier setup github`.",
            docs_path="/docs/github",
        )
    for secret in REQUIRED_SECRETS:
        needle = f"secrets.{secret}"
        if needle not in text:
            raise InstallError(
                "GITHUB_SECRET_MISSING",
                f"{secret} is not configured in GitHub Actions.",
                cause="The workflow does not reference the required secret.",
                next_action="Run `frontier setup github`.",
                docs_path="/docs/github",
            )
    if "FRONTIER_API_KEY" in (loaded.get("jobs") or {}):
        raise InstallError(
            "GITHUB_WORKFLOW_INVALID",
            "The workflow must not embed API keys.",
            cause="A job key looked like a secret.",
            next_action="Run `frontier setup github`.",
            docs_path="/docs/security",
        )
    return loaded


def write_workflow(path: Path, text: str, *, force: bool = False) -> Path:
    if path.exists() and not force:
        raise InstallError(
            "GITHUB_WORKFLOW_EXISTS",
            f"{path} already exists.",
            cause="Refusing to overwrite an existing Frontier workflow.",
            next_action="Re-run with confirmation, or move the existing file first.",
            docs_path="/docs/github",
        )
    validate_workflow_yaml(text)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    validate_workflow_yaml(path.read_text())
    return path


def api_and_snowflake_secrets_separated(text: str) -> bool:
    loaded = yaml.safe_load(text)
    steps = (((loaded or {}).get("jobs") or {}).get("frontier") or {}).get("steps") or []
    for step in steps:
        env = step.get("env") or {}
        has_api = "FRONTIER_API_KEY" in env
        has_snowflake = "SNOWFLAKE_PASSWORD" in env
        if has_api and has_snowflake:
            return False
    return True
